name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, pypy2, pypy3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Tox and any other packages
      run: pip install tox
    - name: Lint
      if: matrix.python-version == '2.7' || matrix.python-version == '3.7'
      run: |
        pip install flake8
        flake8 pymemcache/
    - name: Run Tests via Tox
      # Run tox using the version of Python in `PATH`
      run: tox -e py
